config/routes.rb
Rails.application.routes.draw do
  root 'home#show'
  get 'identities/new'
  get 'auth/failure', to: 'sessions#failure'

  match "/auth/:provider/callback", to: "sessions#create", via: [:get, :post]
  resource :user, only: [:new]
  resources :sessions, only: [:new, :destroy]

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
end

app/models/identity.rb
class Identity < OmniAuth::Identity::Models::ActiveRecord
  validates_uniqueness_of :email
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authentications
  class << self

    def find_or_create_by_omniauth(auth)
      find_by_omniauth(auth) || create_with_omniauth(auth)
    end

    def find_by_omniauth(auth)
      authentication = Authentication.where(provider: auth['provider'], uid: auth['uid']).first
      authentication.user if authentication
    end

    def create_with_omniauth(auth)
      info = auth['info']
      user = nil
      User.transaction do
        user = User.create!(user_params(auth))
        user.authentications.create!(auth_params(auth))
      end
      user
    end

    private
    def user_params(hash)
      info = hash["info"]
      {
        "name" => info["name"]
      }
    end

    def auth_params(hash)
      info = hash["info"]
      credentials = hash["credentials"]
      {
        provider: hash["provider"],
        uid: hash["uid"],
        screen_name: info["nickname"],
        access_token: credentials["token"],
        secret: credentials["secret"],
        name: info["name"]
      }
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/identities_controller.rb
class IdentitiesController < ApplicationController
  def new
    @identity = env['omniauth.identity']
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def destroy
    reset_session
    redirect_to root_url
  end

  def create
    auth = request.env["omniauth.auth"]
    user = User.find_or_create_by_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in!"
  end

  def failure
    flash[:notice] = params[:message]
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @identity = self.env['omniauth.identity'] || Identity.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/show.html.slim
h1
  | This is top page

app/views/identities/new.html.slim
= form_tag "/auth/identity/register" do
  - if @identity && @identity.errors.any?
    .error_messages
      h2
        = pluralize(@identity.errors.count, "error")
        | prohibited this account from being saved
      ul
       - @identity.errors.full_messages.each do |msg|
        li= msg
  .field
    = label_tag :name
    br
    = text_field_tag :name, @identity.try(:name)
  .field
    = label_tag :email
    br
    = text_field_tag :email, @identity.try(:email)
  .field
    = label_tag :password
    br
    = password_field_tag :password
  .field
    = label_tag :password_confirmation
    br
    = password_field_tag :password_confirmation
  .actions
    = submit_tag "Register"

app/views/layouts/application.html.slim
doctype html
html
  head
    title AuthApp
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width"
  body
    header
      .container.nav
        .row
          - if current_user
            .col.offset-sm-8
              span.icon-home
              = "#{current_user.name} さん"
              span.icon-home
              = link_to 'signout', session_path(id: current_user), method: :delete
          - else
            .col.offset-sm-8
              span.icon-home
              = link_to 'signin', new_session_path
              span.icon-home
              = link_to 'signup', new_user_path

    .container
      = yield
  </html>

app/views/users/new.html.slim
h1 Signup

- @identity.errors.full_messages.each do |message|
  ul
     qi= message

= form_for @identity, url: '/auth/identity/register' do
  .row
    .field.col.md-6
      = label 'email', :email
      = text_field_tag :email, '', class: 'form-control'
  .row
    .field.col.md-6
      = label 'email', :password
      = password_field_tag :password, '', class: 'form-control'
  .row
    .field.col.md-6
      = label 'email(confirm)', :password_confirmation
      = password_field_tag :password_confirmation, '', class: 'form-control'
  .row
    .field.col.md-6
      = submit_tag 'Save changes', class: 'btn'